/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TabPanelInterface } from "./components/ip-tab-panel/interface/tab-panel.interface";
export namespace Components {
    interface IpTabPanel {
        "tabPanelHeaders": TabPanelInterface[] | string;
        "tabPanelTitle": string;
    }
}
declare global {
    interface HTMLIpTabPanelElement extends Components.IpTabPanel, HTMLStencilElement {
    }
    var HTMLIpTabPanelElement: {
        prototype: HTMLIpTabPanelElement;
        new (): HTMLIpTabPanelElement;
    };
    interface HTMLElementTagNameMap {
        "ip-tab-panel": HTMLIpTabPanelElement;
    }
}
declare namespace LocalJSX {
    interface IpTabPanel {
        "tabPanelHeaders"?: TabPanelInterface[] | string;
        "tabPanelTitle"?: string;
    }
    interface IntrinsicElements {
        "ip-tab-panel": IpTabPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-tab-panel": LocalJSX.IpTabPanel & JSXBase.HTMLAttributes<HTMLIpTabPanelElement>;
        }
    }
}
